import fs from 'node:fs/promises';
import path from 'node:path';
import { MongoClient, ObjectId } from 'mongodb';
import { expect, test, type BrowserContext, type BrowserContextOptions, type Page } from '@playwright/test';
import { loginFixture, type FixtureLogin } from './fixtures.ts';

const root = path.resolve(__dirname, '..', '..', '..');
const envFile = async (file: string): Promise<Record<string, string>> => Object.fromEntries((await fs.readFile(file, 'utf8')).split(/\r?\n/u).filter(Boolean).map((line) => { const at = line.indexOf('='); return [line.slice(0, at), line.slice(at + 1)]; }));
const sid = async (context: BrowserContext) => { const raw = ((await context.cookies()).find(({ name }) => name === '__Secure-wb_refresh')?.value ?? '').split('.')[0]; if (!ObjectId.isValid(raw) || raw.length !== 24) throw new Error('refresh session id unavailable'); return new ObjectId(raw); };
const credentialCount = async (context: BrowserContext) => (await context.cookies()).filter(({ domain, name }) => domain === 'webtopup.local.test' && ['__Secure-wb_refresh','__Secure-wb_rotation_recovery','wb_csrf'].includes(name)).length;
async function apiLogin(page: Page, fixture: FixtureLogin): Promise<number> { await page.goto('/vite.svg'); return page.evaluate(async (fixture) => { const { apiV2 } = await import('/src/api/index.ts'); const response = await apiV2.post(fixture.loginEndpoint, { email: fixture.email, password: fixture.password, rememberMe: false }, { _skipAuthRefresh: true }); Object.assign(window, { __expiryApi: apiV2 }); return response.status; }, fixture); }

test.describe.configure({ timeout: 150_000 });

test('staff warning locks through the production activity controller and unlocks through production UI', async ({ browser }, testInfo) => {
  const mobile = testInfo.project.name === 'chromium-mobile'; const fixture = await loginFixture(`staff-idle-${mobile ? 'mobile' : 'desktop'}`); const shared = await envFile(path.join(root, '.dev-verification/env/shared.env')); const mongo = new MongoClient(shared.MONGO_URI!); const context = await browser.newContext(testInfo.project.use as BrowserContextOptions); const page = await context.newPage(); let sessionId: ObjectId | null = null; let userId: ObjectId | null = null; let primary: unknown = null; const teardown: unknown[] = [];
  try {
    await mongo.connect(); const user = await mongo.db(shared.MONGO_DB).collection('users').findOne({ email: fixture.email }, { projection: { _id: 1 } }); userId = user?._id ?? null; expect(Boolean(userId)).toBe(true);
    const sessions = mongo.db(shared.MONGO_DB).collection('authsessions');
    const pageErrorNames: string[] = []; page.on('pageerror', (error) => pageErrorNames.push(error.name));
    let loginRole: string | null = null; const unlockResults: Array<{ status: number; code: string | null }> = []; page.on('response', async (response) => { const pathname = new URL(response.url()).pathname; if (pathname === `/api/v2${fixture.loginEndpoint}` && response.status() === 200) { const data = await response.json(); loginRole = typeof data?.user?.role === 'string' ? data.user.role : null; } if (pathname === '/api/v2/auth/unlock') { const data = await response.json().catch(() => null); unlockResults.push({ status: response.status(), code: typeof data?.code === 'string' ? data.code : typeof data?.error?.code === 'string' ? data.error.code : null }); } });
    let activityRequestObserved = false; page.on('request', (request) => { if (new URL(request.url()).pathname === '/api/v2/auth/activity-status') activityRequestObserved = true; });
    let releaseActivityStatus!: () => void; const activityStatusBarrier = new Promise<void>((resolve) => { releaseActivityStatus = resolve; });
    let activityStatusReleased = false; await page.route('**/api/v2/auth/activity-status', async (route) => { await activityStatusBarrier; activityStatusReleased = true; await route.continue(); });
    await page.goto(fixture.loginPath);
    await page.getByLabel('Email').fill(fixture.email);
    await page.getByLabel('Password').fill(fixture.password);
    await page.getByRole('button', { name: 'Masuk sekarang' }).click();
    await expect(page).toHaveURL(/\/admin\/dashboard$/);
    await expect(page.getByRole('button', { name: 'Keluar dari admin' })).toBeVisible();
    await expect.poll(() => activityRequestObserved, { timeout: 20_000 }).toBe(true);
    sessionId = await sid(context);
    const warningDeadline = await sessions.updateOne({ userId, sessionId }, { $set: { idleExpiresAt: new Date(Date.now() + 8_000) } }); expect(warningDeadline.matchedCount).toBe(1);
    releaseActivityStatus();
    await expect.poll(() => loginRole).toBe('cs');
    expect(pageErrorNames).toEqual([]);
    await expect.poll(() => activityStatusReleased, { timeout: 20_000 }).toBe(true);
    await expect(page.getByRole('status').filter({ hasText: 'Sesi akan dikunci' })).toBeVisible();
    await expect(page.getByRole('dialog', { name: 'Sesi dikunci' })).toBeVisible({ timeout: 15_000 });
    const authoritativeLock = await page.evaluate(async () => { const { apiV2 } = await import('/src/api/index.ts'); try { await apiV2.get('/auth/activity-status'); return { status: 200, code: null }; } catch (error) { const response = (error as { response?: { status?: number; data?: { error?: { code?: string }; code?: string } } }).response; return { status: response?.status ?? 0, code: response?.data?.error?.code ?? response?.data?.code ?? null }; } }); expect(authoritativeLock).toEqual({ status: 401, code: 'AUTH_IDLE_LOCKED' });
    await expect.poll(async () => (await sessions.findOne({ userId, sessionId }, { projection: { status: 1 } }))?.status).toBe('locked');
    const locked = await mongo.db(shared.MONGO_DB).collection('authsessions').findOne({ userId, sessionId }, { projection: { status: 1, refreshGeneration: 1 } }); expect({ locked: locked?.status === 'locked', generation: locked?.refreshGeneration }).toEqual({ locked: true, generation: 0 });
    const dialog = page.getByRole('dialog', { name: 'Sesi dikunci' }); await dialog.getByLabel('Password').fill(`${fixture.password}-wrong`); await dialog.getByRole('button', { name: 'Buka sesi' }).click(); await expect.poll(() => unlockResults.length, { timeout: 60_000 }).toBe(1); if (unlockResults[0]?.code !== 'REAUTH_PASSWORD_INVALID') throw new Error(`unlock result ${JSON.stringify(unlockResults)}`); await expect(dialog.getByRole('alert')).toBeVisible(); await expect(dialog).toBeVisible();
    await dialog.getByLabel('Password').fill(fixture.password); await dialog.getByRole('button', { name: 'Buka sesi' }).click(); await expect.poll(() => unlockResults.length, { timeout: 60_000 }).toBe(2); if (unlockResults[1]?.status !== 200) throw new Error(`unlock result ${JSON.stringify(unlockResults)}`); await expect(dialog).toBeHidden({ timeout: 20_000 }); await expect(page).toHaveURL(/\/admin\/dashboard$/);
    const unlocked = await mongo.db(shared.MONGO_DB).collection('authsessions').findOne({ userId, sessionId }, { projection: { status: 1, refreshGeneration: 1, unlockPasswordAttempts: 1, idleExpiresAt: 1 } }); expect({ active: unlocked?.status === 'active', generation: unlocked?.refreshGeneration, attemptsReset: unlocked?.unlockPasswordAttempts === 0, deadlineFuture: unlocked?.idleExpiresAt instanceof Date && unlocked.idleExpiresAt.getTime() > Date.now() }).toEqual({ active: true, generation: 1, attemptsReset: true, deadlineFuture: true });
    if (mobile) expect({ narrow: page.viewportSize()!.width < 600, touch: await page.evaluate(() => navigator.maxTouchPoints > 0) }).toEqual({ narrow: true, touch: true });
  } catch (error) { primary = error; }
  finally { if (userId && sessionId) try { await mongo.db(shared.MONGO_DB).collection('authsessions').updateMany({ userId, sessionId, status: { $in: ['active','locked'] } }, { $set: { status: 'revoked', ownsSlot: false, revokeReason: 'verification_cleanup' } }); } catch (error) { teardown.push(error); } try { await context.close(); } catch (error) { teardown.push(error); } try { await mongo.close(); } catch (error) { teardown.push(error); } if (primary && teardown.length) throw new AggregateError([primary, ...teardown], 'idle verification and cleanup failed'); if (primary) throw primary; if (teardown.length) throw new AggregateError(teardown, 'idle cleanup failed'); }
});

test('idle lock is recoverable while absolute expiry is terminal and family-scoped', async ({ browser }, testInfo) => {
  const mobile = testInfo.project.name === 'chromium-mobile'; const fixture = await loginFixture(`staff-expiry-${mobile ? 'mobile' : 'desktop'}`); const shared = await envFile(path.join(root, '.dev-verification/env/shared.env')); const mongo = new MongoClient(shared.MONGO_URI!); const options = testInfo.project.use as BrowserContextOptions; const idleContext = await browser.newContext(options); const healthyContext = await browser.newContext(options); const idlePage = await idleContext.newPage(); const healthyPage = await healthyContext.newPage(); let userId: ObjectId | null = null; const ids: ObjectId[] = []; let primary: unknown = null; const teardown: unknown[] = [];
  try {
    await mongo.connect(); const user = await mongo.db(shared.MONGO_DB).collection('users').findOne({ email: fixture.email }, { projection: { _id: 1 } }); userId = user?._id ?? null; expect(Boolean(userId)).toBe(true); expect(await apiLogin(idlePage, fixture)).toBe(200); ids.push(await sid(idleContext)); expect(await apiLogin(healthyPage, fixture)).toBe(200); ids.push(await sid(healthyContext));
    await mongo.db(shared.MONGO_DB).collection('authsessions').updateOne({ userId, sessionId: ids[0] }, { $set: { idleExpiresAt: new Date(Date.now() - 1_000) } });
    const idleOutcome = await idlePage.evaluate(async () => { const api = (window as never as { __expiryApi: any }).__expiryApi; try { await api.post('/auth/refresh', {}); return { status: 200, code: null }; } catch (error) { const response = (error as { response?: { status?: number; data?: { error?: { code?: string } } } }).response; return { status: response?.status ?? 0, code: response?.data?.error?.code ?? null }; } }); expect(idleOutcome).toEqual({ status: 423, code: 'AUTH_IDLE_LOCKED' }); expect(await credentialCount(idleContext)).toBe(3);
    const idleRow = await mongo.db(shared.MONGO_DB).collection('authsessions').findOne({ userId, sessionId: ids[0] }, { projection: { status: 1 } }); expect(['active','locked'].includes(idleRow?.status)).toBe(true);
    await mongo.db(shared.MONGO_DB).collection('authsessions').updateOne({ userId, sessionId: ids[0] }, { $set: { absoluteExpiresAt: new Date(Date.now() - 1_000) } });
    const expired = await idlePage.evaluate(async () => { const api = (window as never as { __expiryApi: any }).__expiryApi; try { await api.post('/auth/refresh', {}); return { status: 200, code: null }; } catch (error) { const response = (error as { response?: { status?: number; data?: { error?: { code?: string } } } }).response; return { status: response?.status ?? 0, code: response?.data?.error?.code ?? null }; } }); expect(expired).toEqual({ status: 401, code: 'AUTH_SESSION_EXPIRED' }); expect(await credentialCount(idleContext)).toBe(0);
    const healthy = await healthyPage.evaluate(async () => { const api = (window as never as { __expiryApi: any }).__expiryApi; try { const response = await api.post('/auth/refresh', {}); return { status: response.status, code: null }; } catch (error) { const response = (error as { response?: { status?: number; data?: { error?: { code?: string } } } }).response; return { status: response?.status ?? 0, code: response?.data?.error?.code ?? null }; } }); expect(healthy).toEqual({ status: 200, code: null });
    const healthyRow = await mongo.db(shared.MONGO_DB).collection('authsessions').findOne({ userId, sessionId: ids[1] }, { projection: { status: 1, ownsSlot: 1, refreshGeneration: 1 } }); expect({ active: healthyRow?.status === 'active', ownsSlot: healthyRow?.ownsSlot, generation: healthyRow?.refreshGeneration }).toEqual({ active: true, ownsSlot: true, generation: 1 });
    if (mobile) expect(await Promise.all([idlePage, healthyPage].map(async (page) => ({ narrow: page.viewportSize()!.width < 600, touch: await page.evaluate(() => navigator.maxTouchPoints > 0) })))).toEqual([{ narrow: true, touch: true }, { narrow: true, touch: true }]);
  } catch (error) { primary = error; }
  finally { if (userId && ids.length) try { await mongo.db(shared.MONGO_DB).collection('authsessions').updateMany({ userId, sessionId: { $in: ids }, status: { $in: ['active','locked'] } }, { $set: { status: 'revoked', ownsSlot: false, revokeReason: 'verification_cleanup' } }); } catch (error) { teardown.push(error); } for (const context of [idleContext, healthyContext]) try { await context.close(); } catch (error) { teardown.push(error); } try { await mongo.close(); } catch (error) { teardown.push(error); } if (primary && teardown.length) throw new AggregateError([primary, ...teardown], 'expiry verification and cleanup failed'); if (primary) throw primary; if (teardown.length) throw new AggregateError(teardown, 'expiry cleanup failed'); }
});
