import fs from 'node:fs/promises';
import path from 'node:path';
import { MongoClient, ObjectId } from 'mongodb';
import { expect, test, type BrowserContext, type BrowserContextOptions, type Page } from '@playwright/test';
import { loginFixture } from './fixtures.ts';

const root = path.resolve(__dirname, '..', '..', '..');
const envFile = async (file: string): Promise<Record<string, string>> => Object.fromEntries((await fs.readFile(file, 'utf8')).split(/\r?\n/u).filter(Boolean).map((line) => { const at = line.indexOf('='); return [line.slice(0, at), line.slice(at + 1)]; }));
const sid = async (context: BrowserContext) => new ObjectId(((await context.cookies()).find(({ name }) => name === '__Secure-wb_refresh')?.value ?? '').split('.')[0]);

test.describe.configure({ timeout: 90_000 });

for (const role of ['staff', 'member'] as const) test(`${role} device limit requires explicit replacement and preserves the bounded family count`, async ({ browser }, testInfo) => {
  const mobile = testInfo.project.name === 'chromium-mobile'; const limit = role === 'staff' ? 2 : 5;
  const fixture = await loginFixture(`${role}-replacement-${mobile ? 'mobile' : 'desktop'}`);
  const shared = await envFile(path.join(root, '.dev-verification/env/shared.env')); const mongo = new MongoClient(shared.MONGO_URI!); const options = testInfo.project.use as BrowserContextOptions;
  const contexts: BrowserContext[] = []; const pages: Page[] = []; const captured: ObjectId[] = []; let userId: ObjectId | null = null; let primaryError: unknown = null; let cleanupError: unknown = null;
  try {
    await mongo.connect(); const user = await mongo.db(shared.MONGO_DB).collection('users').findOne({ email: fixture.email }, { projection: { _id: 1 } }); userId = user?._id ?? null; expect(Boolean(userId)).toBe(true);
    for (let index = 0; index < limit + 1; index += 1) { const context = await browser.newContext(options); contexts.push(context); pages.push(await context.newPage()); }
    for (let index = 0; index < limit; index += 1) {
      await pages[index]!.goto('/vite.svg');
      const result = await pages[index]!.evaluate(async ({ fixture, index }) => { const { apiV2 } = await import('/src/api/index.ts'); const response = await apiV2.post(fixture.loginEndpoint, { email: fixture.email, password: fixture.password, rememberMe: false, deviceName: `Owned device ${index}` }, { _skipAuthRefresh: true }); Object.assign(window, { __ownedApi: apiV2 }); return { status: response.status, accessPresent: typeof response.data?.accessToken === 'string' }; }, { fixture, index });
      expect(result).toEqual({ status: 200, accessPresent: true }); captured.push(await sid(contexts[index]!));
    }
    const replacement = pages[limit]!; await replacement.goto(fixture.loginPath);
    await replacement.evaluate(async () => { const { apiV2 } = await import('/src/api/index.ts'); const interceptorId = apiV2.interceptors.response.use(undefined, (error) => { const data = error?.response?.data; const sessions = Array.isArray(data?.sessions) ? data.sessions : []; const selected = sessions.find((session: { deviceLabel?: string }) => session.deviceLabel === 'Owned device 0'); if (data?.code === 'AUTH_DEVICE_LIMIT_REACHED' && typeof data.challengeToken === 'string' && typeof selected?.sessionId === 'string') Object.assign(window, { __replacementReplay: { apiV2, interceptorId, challenge: data.challengeToken, selected: selected.sessionId, count: sessions.length, summariesExact: sessions.every((session: Record<string, unknown>) => JSON.stringify(Object.keys(session).sort()) === JSON.stringify(['createdAt','deviceLabel','ipContext','lastUsedAt','sessionId','userAgentSummary'])), credentialFields: Object.keys(data).some((key) => /accessToken|refreshToken|recoveryToken/i.test(key)) } }); return Promise.reject(error); }); });
    await replacement.getByLabel('Email').fill(fixture.email); await replacement.getByLabel('Password').fill(fixture.password); await replacement.getByRole('button', { name: 'Masuk sekarang' }).click();
    const dialog = replacement.getByRole('dialog', { name: 'Pilih perangkat untuk dikeluarkan' }); await expect(dialog).toBeVisible();
    const limited = await replacement.evaluate(() => { const state = (window as never as { __replacementReplay?: { count: number; summariesExact: boolean; credentialFields: boolean } }).__replacementReplay; return { captured: Boolean(state), count: state?.count ?? 0, summariesExact: state?.summariesExact ?? false, credentialFields: state?.credentialFields ?? true }; });
    expect(limited).toEqual({ captured: true, count: limit, summariesExact: true, credentialFields: false });
    const challengeCookies = (await contexts[limit]!.cookies()).filter(({ domain }) => domain === 'webtopup.local.test');
    expect({ credentialCount: challengeCookies.filter(({ name }) => ['__Secure-wb_refresh','__Secure-wb_rotation_recovery'].includes(name)).length, csrfPresent: challengeCookies.some(({ name }) => name === 'wb_csrf') }).toEqual({ credentialCount: 0, csrfPresent: true });
    const before = await mongo.db(shared.MONGO_DB).collection('authsessions').countDocuments({ userId, status: 'active', ownsSlot: true }); expect(before).toBe(limit);
    await dialog.locator('label').filter({ hasText: 'Owned device 0' }).locator('input[type="radio"]').check();
    const confirmation = dialog.locator('input[type="checkbox"]'); await expect(confirmation).toBeEnabled(); await confirmation.check();
    await dialog.getByRole('button', { name: 'Keluarkan & lanjutkan' }).click();
    await expect(dialog).toBeHidden(); await expect(replacement).toHaveURL(role === 'staff' ? /\/admin\/dashboard$/ : /\/dashboard$/);
    const replacementSid = await sid(contexts[limit]!); captured.push(replacementSid);
    const replayProjection = { sessionId: 1, replacedFromSessionId: 1, status: 1, ownsSlot: 1, refreshGeneration: 1 };
    const beforeReplayRows = await mongo.db(shared.MONGO_DB).collection('authsessions').find({ userId }, { projection: replayProjection }).sort({ sessionId: 1 }).toArray();
    const challengeReplay = await replacement.evaluate(async () => { const state = (window as never as { __replacementReplay: any }).__replacementReplay; const sanitized = (error: unknown) => { const response = (error as { response?: { status?: number; data?: { error?: { code?: string }; code?: string } } }).response; return { status: response?.status ?? 0, code: response?.data?.error?.code ?? response?.data?.code ?? null }; }; try { let sameStatus = 0; let sameCode: string | null = null; try { sameStatus = (await state.apiV2.post('/auth/device-selection', { challengeToken: state.challenge, revokeSessionId: state.selected })).status; } catch (error) { const result = sanitized(error); sameStatus = result.status; sameCode = result.code; } let listStatus = 0; let alternatePresent = false; let other: string | undefined; try { const response = await state.apiV2.get('/auth/sessions'); listStatus = response.status; other = response.data.sessions.find((session: { sessionId: string }) => session.sessionId !== state.selected)?.sessionId; alternatePresent = typeof other === 'string' && other.length > 0 && other !== state.selected; } catch (error) { listStatus = sanitized(error).status; } let conflictStatus = 0; let conflictCode: string | null = null; if (alternatePresent) try { await state.apiV2.post('/auth/device-selection', { challengeToken: state.challenge, revokeSessionId: other }); conflictStatus = 200; } catch (error) { const result = sanitized(error); conflictStatus = result.status; conflictCode = result.code; } return { sameStatus, sameCode, listStatus, alternatePresent, conflictStatus, conflictCode }; } finally { state.apiV2.interceptors.response.eject(state.interceptorId); delete (window as never as { __replacementReplay?: unknown }).__replacementReplay; } });
    expect(challengeReplay).toEqual({ sameStatus: 200, sameCode: null, listStatus: 200, alternatePresent: true, conflictStatus: 409, conflictCode: 'AUTH_CHALLENGE_CONFLICT' });
    const rows = await mongo.db(shared.MONGO_DB).collection('authsessions').find({ userId }, { projection: replayProjection }).sort({ sessionId: 1 }).toArray();
    expect(JSON.stringify(rows) === JSON.stringify(beforeReplayRows)).toBe(true); const oldRow = rows.find((row) => row.sessionId.equals(captured[0]!)); const replacementRow = rows.find((row) => row.sessionId.equals(replacementSid));
    expect({ activeCount: rows.filter((row) => row.status === 'active' && row.ownsSlot === true).length, oldIdentityAbsent: !oldRow, replacementActive: replacementRow?.status === 'active' && replacementRow?.ownsSlot === true, lineageExact: replacementRow?.replacedFromSessionId?.equals(captured[0]!) === true, generationOne: replacementRow?.refreshGeneration === 1 }).toEqual({ activeCount: limit, oldIdentityAbsent: true, replacementActive: true, lineageExact: true, generationOne: true });
    const terminal = await pages[0]!.evaluate(async () => { const apiV2 = (window as never as { __ownedApi: any }).__ownedApi; try { await apiV2.post('/auth/refresh', {}); return { status: 200, code: null }; } catch (error) { const response = (error as { response?: { status?: number; data?: { error?: { code?: string } } } }).response; return { status: response?.status ?? 0, code: response?.data?.error?.code ?? null }; } }); expect(terminal).toEqual({ status: 401, code: 'AUTH_TOKEN_INVALID' });
    const clearedCookies = (await contexts[0]!.cookies()).filter(({ domain, name }) => domain === 'webtopup.local.test' && ['__Secure-wb_refresh','__Secure-wb_rotation_recovery','wb_csrf'].includes(name)).map(({ name, domain, path, secure }) => ({ name, domain, path, secure })); expect(clearedCookies).toEqual([]);
    const survivor = await pages[1]!.evaluate(async () => { const apiV2 = (window as never as { __ownedApi: any }).__ownedApi; try { const response = await apiV2.post('/auth/refresh', {}); return { status: response.status, code: null }; } catch (error) { const response = (error as { response?: { status?: number; data?: { error?: { code?: string } } } }).response; return { status: response?.status ?? 0, code: response?.data?.error?.code ?? null }; } }); expect(survivor).toEqual({ status: 200, code: null });
    const survivorRows = await mongo.db(shared.MONGO_DB).collection('authsessions').find({ userId, sessionId: { $in: captured.slice(1, limit) } }, { projection: { sessionId: 1, status: 1, ownsSlot: 1, refreshGeneration: 1 } }).toArray();
    expect({ count: survivorRows.length, allActive: survivorRows.every((row) => row.status === 'active' && row.ownsSlot === true), representativeRotated: survivorRows.find((row) => row.sessionId.equals(captured[1]!))?.refreshGeneration === 1, untouchedCount: survivorRows.filter((row) => !row.sessionId.equals(captured[1]!) && row.refreshGeneration === 0).length }).toEqual({ count: limit - 1, allActive: true, representativeRotated: true, untouchedCount: limit - 2 });
    if (mobile) expect(await Promise.all(pages.map(async (page) => ({ narrow: page.viewportSize()!.width < 600, touch: await page.evaluate(() => navigator.maxTouchPoints > 0) })))).toEqual(Array.from({ length: limit + 1 }, () => ({ narrow: true, touch: true })));
  } catch (error) { primaryError = error; }
  finally { if (pages.at(-1)) try { await pages.at(-1)!.evaluate(() => { const state = (window as never as { __replacementReplay?: { apiV2?: { interceptors?: { response?: { eject?: (id: number) => void } } }; interceptorId?: number } }).__replacementReplay; if (state?.apiV2?.interceptors?.response?.eject && typeof state.interceptorId === 'number') state.apiV2.interceptors.response.eject(state.interceptorId); delete (window as never as { __replacementReplay?: unknown }).__replacementReplay; }); } catch (error) { cleanupError = error; } if (userId && captured.length) try { await mongo.db(shared.MONGO_DB).collection('authsessions').updateMany({ userId, sessionId: { $in: captured }, status: { $in: ['active','locked'] } }, { $set: { status: 'revoked', ownsSlot: false, revokeReason: 'verification_cleanup' } }); } catch (error) { cleanupError = cleanupError ? new AggregateError([cleanupError, error], 'browser and session cleanup failed') : error; } const closes = await Promise.allSettled(contexts.map((context) => context.close())); let mongoError: unknown = null; try { await mongo.close(); } catch (error) { mongoError = error; } const closeErrors = closes.flatMap((result) => result.status === 'rejected' ? [result.reason] : []); const teardownErrors = [cleanupError, ...closeErrors, mongoError].filter(Boolean); if (primaryError && teardownErrors.length) throw new AggregateError([primaryError, ...teardownErrors], 'device replacement verification and cleanup failed'); if (primaryError) throw primaryError; if (teardownErrors.length === 1) throw teardownErrors[0]; if (teardownErrors.length > 1) throw new AggregateError(teardownErrors, 'device replacement cleanup failed'); }
});
