import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import { MongoClient } from 'mongodb';
import { expect, test } from '@playwright/test';
import { loginFixture } from '../e2e/fixtures.ts';
import { clearFaultEvidence, readFaultEvidence, withFault } from '../faults.ts';

const root = path.resolve(__dirname, '..', '..', '..');
const readEnv = async (file: string): Promise<Record<string, string>> => Object.fromEntries((await fs.readFile(file, 'utf8')).split(/\r?\n/u).filter(Boolean).map((line) => { const at = line.indexOf('='); return [line.slice(0, at), line.slice(at + 1)]; }));
function decodeBase32(secret: string): Buffer { let bits = 0; let value = 0; const out: number[] = []; for (const c of secret) { const d = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'.indexOf(c); value = (value << 5) | d; bits += 5; if (bits >= 8) { out.push((value >> (bits - 8)) & 255); bits -= 8; } } return Buffer.from(out); }
function otp(secret: string) { const input = Buffer.alloc(8); input.writeBigUInt64BE(BigInt(Math.floor(Date.now() / 30_000))); const digest = crypto.createHmac('sha1', decodeBase32(secret)).update(input).digest(); const offset = digest[19]! & 15; return String(((((digest[offset]! & 127) << 24) | (digest[offset + 1]! << 16) | (digest[offset + 2]! << 8) | digest[offset + 3]!) % 1_000_000)).padStart(6, '0'); }

test.describe.configure({ timeout: 120_000 });
test('balance and refund stable keys produce one effect, conflict on changed fingerprint, and fence parallel duplicates', async ({ page }) => {
  const actor = await loginFixture('finance-actor'); const [env, nodeEnv, manifest] = await Promise.all([readEnv(path.join(root, '.dev-verification/env/shared.env')), readEnv(path.join(root, '.dev-verification/env/node.env')), fs.readFile(path.join(root, '.dev-verification/fixture-manifest.json'), 'utf8').then(JSON.parse)]); const fixtureRunId = manifest.find((item: any) => item.alias === 'finance-actor')?.fixtureRunId; expect(typeof fixtureRunId).toBe('string'); const mongo = new MongoClient(env.MONGO_URI!); let primary: unknown = null; let actorId: any; let targetId: any; let transactionId: any;
  try {
    await mongo.connect(); const db = mongo.db(env.MONGO_DB); const actorRow = await db.collection('users').findOne({ email: actor.email }, { projection: { _id: 1, twoFactorSecret: 1 } }); const target = await db.collection('users').findOne({ fixtureScenario: 'finance-idempotency-target', fixtureRunId }, { projection: { _id: 1, balance: 1 } }); const transaction = await db.collection('transactions').findOne({ fixtureScenario: 'finance-idempotency-refund', fixtureRunId }, { projection: { _id: 1, user: 1, amount: 1 } }); expect({ actor: Boolean(actorRow), secret: typeof actorRow?.twoFactorSecret === 'string', target: Boolean(target), transaction: Boolean(transaction) }).toEqual({ actor: true, secret: true, target: true, transaction: true }); actorId = actorRow!._id; targetId = target!._id; transactionId = transaction!._id;
    await page.goto(actor.loginPath); await page.getByLabel('Email').fill(actor.email); await page.getByLabel('Password').fill(actor.password); await page.getByRole('button', { name: 'Masuk sekarang' }).click(); await page.getByLabel('Kode OTP').fill(otp(actorRow!.twoFactorSecret)); await page.getByRole('button', { name: 'Verifikasi & masuk' }).click(); await expect(page).toHaveURL(/\/admin\/dashboard$/);
    await page.evaluate(async ({ password, otpCode }) => { const api = (await import('/src/api/index.ts')).apiV2; const grants: Record<string, string> = {}; for (const group of ['finance.adjust_balance', 'finance.refund']) grants[group] = (await api.post('/auth/step-up', { password, otp: otpCode, actionGroup: group })).data.grantToken; Object.assign(window, { __financeVerification: { api, grants } }); }, { password: actor.password, otpCode: otp(actorRow!.twoFactorSecret) });
    const stateDir = path.join(root, '.dev-verification');
    const balanceKey = crypto.randomUUID(); const balanceLost = await withFault({ stateDir, capability: nodeEnv.LOCAL_DESTRUCTIVE_CAPABILITY!, scenario: 'finance_balance_response_loss_after_commit', ttlMs: 5_000 }, () => page.evaluate(async ({ target, key }) => { const v = (window as any).__financeVerification; try { await v.api.post(`/users/${target}/balance`, { type: 'add', amount: 1000, reason: 'task14 deterministic balance verification' }, { headers: { 'Idempotency-Key': key, 'X-Step-Up-Token': v.grants['finance.adjust_balance'] }, _skipAuthRefresh: true }); return { lost: false, status: 200, code: null }; } catch (error) { const response = (error as any).response; return { lost: !response, status: response?.status ?? 0, code: response?.data?.error?.code ?? null }; } }, { target: targetId.toHexString(), key: balanceKey })); expect(balanceLost).toEqual({ lost: false, status: 502, code: null }); await expect.poll(async () => (await readFaultEvidence(stateDir))?.scenario).toBe('finance_balance_response_loss_after_commit');
    const refundKey = crypto.randomUUID(); const refundLost = await withFault({ stateDir, capability: nodeEnv.LOCAL_DESTRUCTIVE_CAPABILITY!, scenario: 'finance_refund_response_loss_after_commit', ttlMs: 5_000 }, () => page.evaluate(async ({ transaction, key }) => { const v = (window as any).__financeVerification; try { await v.api.post(`/transactions/${transaction}/refund`, { reason: 'task14 deterministic refund verification' }, { headers: { 'Idempotency-Key': key, 'X-Step-Up-Token': v.grants['finance.refund'] }, _skipAuthRefresh: true }); return { lost: false, status: 200, code: null }; } catch (error) { const response = (error as any).response; return { lost: !response, status: response?.status ?? 0, code: response?.data?.error?.code ?? null }; } }, { transaction: transactionId.toHexString(), key: refundKey })); expect(refundLost).toEqual({ lost: false, status: 502, code: null }); await expect.poll(async () => (await readFaultEvidence(stateDir))?.scenario).toBe('finance_refund_response_loss_after_commit');
    const result = await page.evaluate(async ({ target, transaction, balanceKey, refundKey }) => {
      const api = (await import('/src/api/index.ts')).apiV2;
      const v = (window as any).__financeVerification; const grant = async (group: string) => v.grants[group] as string;
      const request = async (route: string, body: object, key: string, token: string) => { try { const response = await api.post(route, body, { headers: { 'Idempotency-Key': key, 'X-Step-Up-Token': token }, _skipAuthRefresh: true }); return { status: response.status, code: null }; } catch (error) { const response = (error as any).response; return { status: response?.status ?? 0, code: response?.data?.error?.code ?? null }; } };
      const balanceToken = await grant('finance.adjust_balance'); const balanceBody = { type: 'add', amount: 1000, reason: 'task14 deterministic balance verification' }; const balanceFirst = await request(`/users/${target}/balance`, balanceBody, balanceKey, balanceToken); const balanceReplay = await request(`/users/${target}/balance`, balanceBody, balanceKey, balanceToken); const balanceConflict = await request(`/users/${target}/balance`, { ...balanceBody, amount: 1001 }, balanceKey, balanceToken); const parallelKey = globalThis.crypto.randomUUID(); const parallel = await Promise.all(Array.from({ length: 6 }, () => request(`/users/${target}/balance`, balanceBody, parallelKey, balanceToken)));
      const refundToken = await grant('finance.refund'); const refundBody = { reason: 'task14 deterministic refund verification' }; const refundFirst = await request(`/transactions/${transaction}/refund`, refundBody, refundKey, refundToken); const refundReplay = await request(`/transactions/${transaction}/refund`, refundBody, refundKey, refundToken); const refundConflict = await request(`/transactions/${transaction}/refund`, { reason: 'task14 changed refund fingerprint' }, refundKey, refundToken);
      return { balanceFirst, balanceReplay, balanceConflict, parallel, refundFirst, refundReplay, refundConflict };
    }, { target: targetId.toHexString(), transaction: transactionId.toHexString(), balanceKey, refundKey });
    if (result.balanceFirst.status !== 200) throw new Error(`finance boundary ${JSON.stringify(result)}`); expect(result.balanceFirst.status).toBe(200); expect(result.balanceReplay.status).toBe(200); expect(result.balanceConflict.status).toBe(409); expect(result.parallel.filter((item) => item.status === 200).length).toBeGreaterThanOrEqual(1); expect(result.parallel.every((item) => [200, 409, 425].includes(item.status))).toBe(true); expect(result.refundFirst.status).toBe(200); expect(result.refundReplay.status).toBe(200); expect(result.refundConflict.status).toBe(409);
    const finalTarget = await db.collection('users').findOne({ _id: targetId }, { projection: { balance: 1 } }); expect(finalTarget?.balance).toBe((target!.balance ?? 0) + 1000 + 1000 + transaction!.amount); const records = await db.collection('idempotencyrecords').find({ actorId }, { projection: { routeKey: 1, status: 1, responseStatus: 1 } }).toArray(); expect(records.filter((row) => row.status === 'completed' && row.responseStatus === 200)).toHaveLength(3); expect(await db.collection('transactions').countDocuments({ _id: transactionId, refunded: true, refundPhase: 'audited' })).toBe(1);
  } catch (error) { primary = error; }
  const cleanupErrors: unknown[] = []; for (const cleanup of [() => clearFaultEvidence(path.join(root, '.dev-verification')), async () => { if (actorId) await mongo.db(env.MONGO_DB).collection('authsessions').updateMany({ userId: actorId, status: { $in: ['active', 'locked'] } }, { $set: { status: 'revoked', ownsSlot: false, revokeReason: 'verification_cleanup' } }); }, () => mongo.close()]) try { await cleanup(); } catch (error) { cleanupErrors.push(error); }
  if (primary && cleanupErrors.length) throw new AggregateError([primary, ...cleanupErrors], 'idempotency verification and cleanup failed'); if (primary) throw primary; if (cleanupErrors.length) throw new AggregateError(cleanupErrors, 'idempotency cleanup failed');
});
