import { useEffect, useRef, useState, type FormEvent } from 'react';
import { bindIdleLockFocusTrap } from '../../auth/idleLockFocus.ts';

type Props={phase:'active'|'warning'|'locked';idleExpiresAt?:number;requiresOtp?:boolean;error?:string|null;onUnlock(password:string,otp?:string):Promise<void>};
export default function IdleLockScreen({phase,idleExpiresAt,requiresOtp,error,onUnlock}:Props){
 const dialog=useRef<HTMLDivElement>(null); const [password,setPassword]=useState(''); const [otp,setOtp]=useState(''); const [busy,setBusy]=useState(false); const [remaining,setRemaining]=useState(0);
 useEffect(()=>{ if(phase!=='warning'||!idleExpiresAt)return; const update=()=>setRemaining(Math.max(0,Math.ceil((idleExpiresAt-Date.now())/1000))); update(); const id=window.setInterval(update,1000); return()=>window.clearInterval(id); },[phase,idleExpiresAt]);
 useEffect(()=>{ if(phase!=='locked'||typeof document==='undefined')return; return bindIdleLockFocusTrap(dialog.current,document); },[phase]);
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!password||busy)return;setBusy(true);try{await onUnlock(password,otp||undefined);setPassword('');setOtp('');}finally{setBusy(false);}};
 if(phase==='active')return null;
 if(phase==='warning')return <div role="status" aria-live="polite" className="fixed bottom-5 right-5 z-[100] max-w-sm rounded-xl border border-amber-400 bg-amber-50 p-4 text-amber-950 shadow-xl"><strong>Sesi akan dikunci</strong><p className="mt-1 text-sm">Berinteraksi dengan halaman dalam {Math.ceil(remaining/60)} menit agar sesi tetap aktif.</p></div>;
 return <div className="fixed inset-0 z-[200] grid place-items-center bg-slate-950/80 p-4" role="presentation"><div ref={dialog} role="dialog" aria-modal="true" aria-labelledby="idle-lock-title" className="w-full max-w-md rounded-2xl bg-white p-6 text-slate-900 shadow-2xl"><h2 id="idle-lock-title" className="text-xl font-bold">Sesi dikunci</h2><p className="mt-2 text-sm text-slate-600">Masukkan kembali kredensial Anda untuk melanjutkan halaman ini.</p><form onSubmit={submit} className="mt-5 space-y-4"><label className="block text-sm font-semibold">Password<input autoComplete="current-password" type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2" /></label>{requiresOtp&&<label className="block text-sm font-semibold">Kode OTP<input autoComplete="one-time-code" inputMode="numeric" value={otp} onChange={e=>setOtp(e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2" /></label>}{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<button disabled={busy||!password} className="w-full rounded-lg bg-slate-900 px-4 py-2 font-semibold text-white disabled:opacity-50">{busy?'Memverifikasi…':'Buka sesi'}</button></form></div></div>;
}
