import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';
import { X509Certificate } from 'node:crypto';
import { verificationCertificateSpki } from '../certificate.ts';

// The local checkout certificate is generated by setup. This verifies the helper hashes only
// the public SPKI, matching Chromium's scoped allowlist contract.
test('certificate allowlist value is the SHA-256 digest of public SPKI', async (context) => {
  const root = path.resolve(import.meta.dirname, '..', '..', '..');
  const certificatePath = path.join(root, '.dev-verification/certs/webtopup.local.test.pem');
  try { await fs.access(certificatePath); } catch { context.skip('run dev-verify setup to generate the isolated certificate'); return; }
  const pem = await fs.readFile(certificatePath);
  const certificate = new X509Certificate(pem);
  const expected = crypto.createHash('sha256')
    .update(certificate.publicKey.export({ type: 'spki', format: 'der' }))
    .digest('base64');
  assert.equal(verificationCertificateSpki(root), expected);
  assert.match(expected, /^[A-Za-z0-9+/]{43}=$/u);
});
